### ISSUE TITLE
maven failed to build the plugin

### ISSUE THREAD

**Issue by naikwadi-sachin** [evosec/export-dependencies-maven-plugin#1]
Hi, when I tried to build the plugin, I get the following error message.
Any comment on it would be appreciated.

sachin@sachin-VirtualBox:~/github/export-dependencies-maven-plugin$ mvn install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building export-dependencies-maven-plugin
[INFO]    task-segment: [install]
[INFO] ------------------------------------------------------------------------
[INFO] [plugin:helpmojo {execution: help-goal}]
[INFO] Using 'UTF-8' encoding to read mojo metadata.
[INFO] Mojo extractor with id: java-javadoc found 0 mojo descriptors.
[INFO] Mojo extractor with id: java-annotations found 0 mojo descriptors.
[INFO] [plugin:descriptor {execution: default-descriptor}]
[INFO] Using 'UTF-8' encoding to read mojo metadata.
[INFO] Mojo extractor with id: java-javadoc found 0 mojo descriptors.
[INFO] Mojo extractor with id: java-annotations found 0 mojo descriptors.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error extracting plugin descriptor: 'No mojo definitions were found for plugin: de.evosec:export-dependencies-maven-plugin.'

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7 seconds
[INFO] Finished at: Wed Sep 23 16:55:54 EDT 2015
[INFO] Final Memory: 46M/300M
[INFO] ------------------------------------------------------------------------

-Sachin

**Comment by ArloL** [comment]
Hi Sachin,

what is your maven version?

This is my setup

```
$ mvn --version:
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```

Cheers,

Arlo

**Comment by ArloL** [comment]
What strikes me is this part: `[INFO] task-segment: [install]`

I have never seen that in a maven build before.

**Comment by naikwadi-sachin** [comment]
Alright, this is my setup.

$ mvn -version
Apache Maven 2.2.1 (rdebian-14)
Java version: 1.8.0_60
Java home: /usr/java/jdk1.8.0_60/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux" version: "3.19.0-25-generic" arch: "amd64" Family: "unix"

So basically, I am trying to compile and build export-dependecies-maven-plugin and install it in my local maven repo. so then I can use this plugin to convert my maven spring boot project to buck.

Please correct me if my understanding is incorrect.

-Sachin

**Comment by ArloL** [comment]
Are you just trying to use the plugin? Or is there a specific reason you are building yourself?

The plugin is distributed via Maven Central. Therefore you can just call `mvn de.evosec:export-dependencies-maven-plugin:buck` in your Spring Boot project.

But I am not sure whether it will work with a Maven that ancient. [Spring Boot even only supports Maven 3.2+](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#getting-started-system-requirements).

I recommend updating your Maven version.

**Comment by naikwadi-sachin** [comment]
Maven update seems to have solved my issue :+1: 

Thank you Arlo.

-Sachin

**Comment by ArloL** [comment]
I will close the issue then. Let me know if you have any other issues.
